"""
Конфигурационный пакет для Анализатора Калорий
"""

from .messages import (
    WELCOME_MESSAGE, 
    HELP_MESSAGE,
    ANALYSIS_START_MESSAGE,
    ANALYSIS_COMPLETE_PREFIX,
    ERROR_MESSAGES,
    STARTUP_MESSAGES,
    TOKEN_ERROR_MESSAGES,
    SUBSCRIPTION_MESSAGES
)

from .prompts import FOOD_ANALYSIS_PROMPT, API_SETTINGS

__all__ = [
    'WELCOME_MESSAGE',
    'HELP_MESSAGE', 
    'ANALYSIS_START_MESSAGE',
    'ANALYSIS_COMPLETE_PREFIX',
    'ERROR_MESSAGES',
    'STARTUP_MESSAGES',
    'TOKEN_ERROR_MESSAGES',
    'SUBSCRIPTION_MESSAGES',
    'FOOD_ANALYSIS_PROMPT',
    'API_SETTINGS'
]
